# Root directory
root = "."
tmp_dir = "tmp"

# Build settings for Go backend
[build]
cmd = "go build -o ./tmp/main ./server"
bin = "./tmp/main"
full_bin = false
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["client", "tmp", "node_modules"]

# Watching & reload settings
[reload]
delay = 200
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["client", "tmp", "node_modules"]

# Logging colors
[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"

[log]
time = true

# Optional: start React dev server automatically
[dev_server]
cmd = "cd client && npm start"
disable = false
